# Copyright 2017 University of Cincinnati
# All rights reserved. See LICENSE file at:
# https://github.com/MatthewVerbryke/inmoov-ros
# Additional copyright may be held by others, as reflected in the commit history.

inmoov:
 # Publish all joint states ------------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

 #Trajectory Controllers----------------------------------------
  right_arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - right_shoulder_side
      - right_shoulder_up
      - right_bicep_rotate
      - right_elbow
      - right_wrist

  left_arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - left_shoulder_side
      - left_shoulder_up
      - left_bicep_rotate
      - left_elbow
      - left_wrist

  head_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - head_tilt
      - head_updown
      - head_leftright

  hip_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - waist_rotate
      - waist_lean

 # Position Controllers ----------------------------------------
  #Right Hand
  right_thumb_controller:
    type: effort_controllers/JointPositionController
    joint: right_thumbMCP
    pid: {p: 10, i: 1, d: 0.1}

  right_index_controller:
    type: effort_controllers/JointPositionController
    joint: right_indexPIP
    pid: {p: 10, i: 1, d: 0.1}

  right_middle_controller:
    type: effort_controllers/JointPositionController
    joint: right_middlePIP
    pid: {p: 10, i: 1, d: 0.1}

  right_ring_controller:
    type: effort_controllers/JointPositionController
    joint: right_ringMCP
    pid: {p: 10, i: 1, d: 0.1}

  right_pinky_controller:
    type: effort_controllers/JointPositionController
    joint: right_pinkyMCP
    pid: {p: 10, i: 1, d: 0.1}

  #Left Hand
  left_thumb_controller:
    type: effort_controllers/JointPositionController
    joint: left_thumbMCP
    pid: {p: 10, i: 1, d: 0.1}

  left_index_controller:
    type: effort_controllers/JointPositionController
    joint: left_indexPIP
    pid: {p: 10, i: 1, d: 0.1}

  left_middle_controller:
    type: effort_controllers/JointPositionController
    joint: left_middlePIP
    pid: {p: 10, i: 1, d: 0.1}

  left_ring_controller:
    type: effort_controllers/JointPositionController
    joint: left_ringMCP
    pid: {p: 10, i: 1, d: 0.1}

  left_pinky_controller:
    type: effort_controllers/JointPositionController
    joint: left_pinkyMCP
    pid: {p: 10, i: 1, d: 0.1}

  # Head
  jaw_position_controller:
    type: effort_controllers/JointPositionController
    joint: jaw
    pid: {p: 10.0, i: 0, d: 0}

  eyes_updown_position_controller:
    type: effort_controllers/JointPositionController
    joint: eyes_updown
    pid: {p: 1.0, i: 0.01, d: 0}

  eye_leftright_position_controller:
    type: effort_controllers/JointPositionController
    joint: eye_leftright
    pid: {p: 1.0, i: 0.01, d: 0}

 # "Fake" Scaled Position Controllers---------------------------
  # Right Hand
  right_thumbCMC_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_thumbCMC
    pid: {p: 10, i: 1, d: 0.1}

  right_thumbIP_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_thumbIP
    pid: {p: 10, i: 1, d: 0.1}

  right_indexMCP_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_indexMCP
    pid: {p: 10, i: 1, d: 0.1}

  right_indexDIP_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_indexDIP
    pid: {p: 10, i: 1, d: 0.1}

  right_middleMCP_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_middleMCP
    pid: {p: 10, i: 1, d: 0.1}

  right_middleDIP_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_middleDIP
    pid: {p: 10, i: 1, d: 0.1}

  right_ringCMC_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_ringCMC
    pid: {p: 10, i: 1, d: 0.1}

  right_ringPIP_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_ringPIP
    pid: {p: 10, i: 1, d: 0.1}

  right_ringDIP_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_ringDIP
    pid: {p: 10, i: 1, d: 0.1}

  right_pinkyCMC_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_pinkyCMC
    pid: {p: 10, i: 1, d: 0.1}

  right_pinkyPIP_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_pinkyPIP
    pid: {p: 10, i: 1, d: 0.1}

  right_pinkyDIP_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_pinkyDIP
    pid: {p: 10, i: 1, d: 0.1}

  # Left Hand
  left_thumbCMC_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_thumbCMC
    pid: {p: 10, i: 1, d: 0.1}

  left_thumbIP_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_thumbIP
    pid: {p: 10, i: 1, d: 0.1}

  left_indexMCP_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_indexMCP
    pid: {p: 10, i: 1, d: 0.1}

  left_indexDIP_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_indexDIP
    pid: {p: 10, i: 1, d: 0.1}

  left_middleMCP_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_middleMCP
    pid: {p: 10, i: 1, d: 0.1}

  left_middleDIP_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_middleDIP
    pid: {p: 10, i: 1, d: 0.1}

  left_ringCMC_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_ringCMC
    pid: {p: 10, i: 1, d: 0.1}

  left_ringPIP_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_ringPIP
    pid: {p: 10, i: 1, d: 0.1}

  left_ringDIP_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_ringDIP
    pid: {p: 10, i: 1, d: 0.1}

  left_pinkyCMC_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_pinkyCMC
    pid: {p: 10, i: 1, d: 0.1}

  left_pinkyPIP_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_pinkyPIP
    pid: {p: 10, i: 1, d: 0.1}

  left_pinkyDIP_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_pinkyDIP
    pid: {p: 10, i: 1, d: 0.1}


