controller_list:
  - name: fake_right_arm_controller
    joints:
      - right_shoulder_side
      - right_shoulder_up
      - right_bicep_rotate
      - right_elbow
      - right_wrist
  - name: fake_left_arm_controller
    joints:
      - left_shoulder_side
      - left_shoulder_up
      - left_bicep_rotate
      - left_elbow
      - left_wrist
  - name: fake_head_controller
    joints:
      - head_tilt
      - head_updown
      - head_leftright
  - name: fake_hip_controller
    joints:
      - waist_rotate
      - waist_lean
